apiVersion: v1
kind: Pod
metadata:
  name: my-nfs-pod
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-nfs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: my-nfs-volume
    persistentVolumeClaim:
      claimName: my-nfs-pvc
