users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIILzMYJwNJ90Hw6d8CKCpG+5miyXeB8lj6VBnz8Dqc81 ubuntu

packages:
  - openssl
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - net-tools
  - nfs-kernel-server
  - socat
  - gpg

bootcmd:
  - echo 169.254.144.111 conrol01 >> /etc/hosts
  - echo 169.254.144.112 conrol02 >> /etc/hosts
  - echo 169.254.144.201 worker01 >> /etc/hosts
  - echo 169.254.144.202 worker02 >> /etc/hosts
  - echo 169.254.144.203 worker03 >> /etc/hosts
  - echo 169.254.144.204 worker04 >> /etc/hosts
  - echo 169.254.144.205 worker05 >> /etc/hosts
  - echo 169.254.144.199 nfsserver >> /etc/hosts
runcmd:
  - sudo mkdir /data
  - sudo chown -R nobody:nogroup /data
  - sudo chmod -R 777 /data
  - echo '/data *(rw,sync,no_subtree_check)' |  sudo tee -a /etc/exports > /dev/null
  - sudo exportfs -a
  - sudo systemctl restart nfs-kernel-server
  - sudo ufw allow from 10.0.0.0/24 proto tcp to any port 22