users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDO2H4g/GJSQ9J3omcGTyLU3NS7jeyspEgetynOnmEFpqiUBvmrC26Sdo4uAQKqp4eGg9DE9yE7JKc/PxzVqKcKFj6EEyS37/A2UfgNsDKDElICHUi0GiTujkYvdQcU3cnpS3Yep0KVyAjAiRFESHpWhz9OtGTGIslR23WDFDd/2nIQBRxK3hucLUQIvIsl0MbGqU4R9Hbvhi5HgY9/ht42qIcb9dIq41O2/92K44mFgiJH/IjZanMJTMVdHVr27XGvVlbkuuzt+H7ZYRNhn6pjhClw8ipoy++28Hu170O5qHL/ybUNMgxVQBAiVmQNWB9WHU/c2VBO3vD+6m3t9/wY3+Bdq4LZ2InQl+VPPc95vCmYIIOuvRbdYjQ9XrEDsnzr9J0fo7TQ1JUxXPMs33SFp918BQh4agYl2oq9YpxQL/pJXBgjEa4BlhRXKZAt1GLQgPEqRQBPR5hOXR+/Z3u6yROdflE3QdJWTpbsdjBaC/4p90pdIFBrirmPT3q0eR0= ubuntu