apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-pg
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.199
  share: /data
reclaimPolicy:  Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - nfsvers=4.1
